### ISSUE TITLE
Adreno OpenCL gpu frequency

### ISSUE THREAD

**Issue by Saikatsaha1996** [supernovaremnant/bazel-android-opencl#2]
Every time showing Adreno OpenCL gpu frequency only 1 MHz...
Can you help me?..
Why showing...

**Comment by WeiCheng14159** [comment]
Sorry I just saw this message now. Which Adreno GPU do you refer to ?

**Comment by Saikatsaha1996** [comment]
Adreno 650 gpu

**Comment by WeiCheng14159** [comment]
Sorry I don't have experience in Adreno 650. 
Perhaps the frequency of GPU is dynamic (?)

**Comment by Saikatsaha1996** [comment]
![Screenshot_20210708-234503](https://user-images.githubusercontent.com/72664192/125444811-79da1edb-11ff-48c9-a5c9-21dce5208b4f.png)
![Screenshot_2021-04-26-16-33-58-406_com termux](https://user-images.githubusercontent.com/72664192/125444935-c189d327-e889-46a6-babb-f105bf3a9937.jpg)

**Comment by WeiCheng14159** [comment]
Have you read "How to enable performance mode" on page 69 in [this](https://developer.qualcomm.com/download/adrenosdk/adreno-opencl-programming-guide.pdf) docuement ?

**Comment by Saikatsaha1996** [comment]
Omg just awesome ...🥰🥰🥰
Thank you for your information....
I am not a developer but I will try ...
Thank you so much....

It's really helpful for me..
I have only 650 gpu
But I will find another device..

**Comment by WeiCheng14159** [comment]
That happens to me once. Forgot to disable the default power manager for Adreno GPU.
Good luck hacking !

**Comment by Saikatsaha1996** [comment]
> That happens to me once. Forgot to disable the default power manager for Adreno GPU.
> Good luck hacking !

Thank you for your response
Any solution please?
![IMG_20210714_115413](https://user-images.githubusercontent.com/72664192/125573556-e7490dc5-cb5c-4c6b-8cdd-2291df4d856f.jpg)

**Comment by Saikatsaha1996** [comment]
Successfully completed
🥰

But still now showing OpenCL gpu 2.0
Max frequency     1 MHz
